- name: Install Java On Ec2 Instances
  hosts: all
  become: yes
  tasks:
    - name: Install Java OpenJDK 8
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Set JAVA_HOME and PATH for Java (Global Environment)
      copy:
        dest: /etc/profile.d/java.sh
        content: |
          # Set JAVA_HOME to JDK directory
          export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.442.b06-2.el9.x86_64
          export PATH=$JAVA_HOME/bin:$PATH
        mode: '0755'

    - name: Ensure the JAVA_HOME environment is loaded
      shell: source /etc/profile.d/java.sh
      args:
        executable: /bin/bash
      register: result

    - name: Check JAVA_HOME and PATH environment variables
      debug:
        msg: "{{ result.stdout }}"
