---
- name: Create EC2 instance with allocated storage
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        image_id: "ami-09c813fb71547fc4f"  # Corrected parameter
        instance_type: "t2.micro"
        region: "us-east-1"
        count: 1
        vpc_subnet_id: "subnet-083995b999421458a"  # Add your subnet ID (mandatory)
        network:
          assign_public_ip: yes  # Ensures the instance gets a public IP
        volumes:
          - device_name: "/dev/xvda"
            ebs:
              volume_size: 30  # Allocate 30 GB storage
              volume_type: "gp2"  # General Purpose SSD
        tags:  # Corrected from `instance_tags`
          Name: "Hadoop_Instance"
        user_data: |
          #!/bin/bash
          echo "Setting up instance with allocated space"
        wait: yes
      register: ec2_info  # Corrected variable name

    - name: Output instance information
      debug:
        msg: "Instance {{ ec2_info.instances[0].public_ip_address }} is created with 30GB allocated storage."
